# Site Settings
# You can change the settings below in order to customize your website.
name: "TheMadBlogger.com"
title: "TheMadBlogger.com"
description: " Internet's premier location for being torn down. You likely upset me!"
logo: assets/images/madblogger.jpg
favicon: '/assets/images/favicon.ico'
url: https://www.themadblogger.com
baseurl: ""
google_analytics: 'G-ZEWKSGFGHJ' # configured for Google Analytics 4 MEASUREMENT ID
disqus: TheMadBlogger
mailchimp-list: 
include: ["_pages"]
permalink: /:title/

templatemessage: 'Are you mad?'

# Authors
authors:
  TheMadBlogger:
    name: TheMadBlogger
    display_name: TheMadBlogger
    gravatar: 
    email: TheMadBlogger@christoc.com
    web: https://www.themadblogger.com
    twitter: https://twitter.com/RealMadBlogger
    description: "I am TheMadBlogger, you may have upset me. Did I upset you?" 
    
# Plugins
plugins:
  - jekyll_picture_tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
      
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

picture:
  source: "assets/images"
  output: "assets/images_out"
  suppress_warnings: true
  ignore_missing_images: false
  presets:
    default:
      ppi: [1, 1.5]
      source_medium:
        media: "(min-width: 40em)"
        width: "600"
        height: "300"
      source_default:
        width: "300"

defaults:
  - scope:
      path: ""  # An empty string here means all files
      type: "posts"
    values:
      author: "TheMadBlogger"


# exclude:
#  - /assets/images/*